#!/bin/sh
#check for positive or negative number

if [ $# -eq 0 ]
then
echo "$0 You must provide an integer"
exit 1
fi

if [ $1 -ge 0 ] 
then 
echo "$1 is a positve number"
else
echo "$1 is negative number"
fi

